# Generated by Django 4.0.3 on 2022-03-25 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='kid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kid_name', models.CharField(max_length=30)),
                ('kid_age', models.IntegerField()),
                ('parent_phone_number', models.CharField(max_length=10)),
                ('parent_email_address', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.URLField()),
                ('is_Approved', models.BooleanField(default=False)),
                ('approved_by', models.CharField(max_length=40)),
                ('food_group', models.CharField(choices=[('Veg', 'Veg'), ('Fruit', 'Fruit'), ('Grain', 'Grain'), ('Protein', 'Protein'), ('Dairy', 'Dairy'), ('Confectionery', 'Confectionery'), ('Unknown', 'Unknown')], max_length=20)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('kid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.kid')),
            ],
        ),
    ]
